package com.ger.garage.model;

/*

Class mechanic: Represent a mechanic in the system

 */

public class Mechanic {

    private Integer id;
    private String name;

    public Mechanic() {
        // Required empty constructor for Firebase
    }

    public Mechanic(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "id: " + id + " Mechanic: " + this.name;
    }

    public Mechanic(Integer id) {
        this.id = id;
    }


    // This method is static and return a mechanic object using
    // a mechanic string generated by toString()
    // NO MODIFY THIS METHOD DEPENDS ON TOSTRING()
    public static Mechanic valueOf(String mechanic) {

        String id="";

        for (int i = 4; i < mechanic.length(); i++) {

            if (mechanic.charAt(i) == ' ')
                break;
            id = id + mechanic.charAt(i);
        }

        return new Mechanic(Integer.parseInt(id));

    }

}
